### ISSUE TITLE
Is it possible to input_file?

### ISSUE THREAD

**Issue by ifduyue** [mwilliamson/jq.py#107] opened 2024-04-09 11:51 UTC
Hello, 

Is it possible to input_file? So that we don't need to read whole file into python variable.

**Comment by mwilliamson** [comment] 2024-04-11 17:27
Not at the moment, no.

**Comment by mwilliamson** [comment] 2024-08-14 17:21
Closing as a duplicate of #58.

**Closed by mwilliamson** 2024-08-14 17:21 UTC
