### ISSUE TITLE
Error building wheel for jq during "pip install jq"

### ISSUE THREAD

**Issue by rabeeqasem** [mwilliamson/jq.py#90] opened 2023-06-18 18:37 UTC
When attempting to install the `jq` package on Windows 11 using the command `pip install jq`, an error occurs during the process of building the wheel for the package. The error message indicates that the wheel build process for `jq` failed.

```

Building wheel for jq (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for jq (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [5 lines of output]
    running bdist_wheel
    running build
    running build_ext
    Executing: ./configure CFLAGS=-fPIC --prefix=C:\Users\Rabee\AppData\Local\Temp\pip-install-9p4zzb20\jq_55358dac5d0c47a1857c9371a6542fdb\_deps\build\onig-install-6.9.4
    error: [WinError 2] The system cannot find the file specified
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for jq
Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects


```

**Comment by mwilliamson** [comment] 2023-06-18 19:08
I'm afraid Windows isn't currently supported. Closing as a duplicate of #20.

**Closed by mwilliamson** 2023-06-18 19:08 UTC
