### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by menachemsperka** [mwilliamson/jq.py#101] opened 2023-12-26 10:20 UTC
windows PC

`pip install jq
Collecting jq
  Using cached jq-1.6.0.tar.gz (2.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: jq
  Building wheel for jq (pyproject.toml): started
  Building wheel for jq (pyproject.toml): finished with status 'error'
Failed to build jq
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  × Building wheel for jq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Executing: ./configure CFLAGS=-fPIC --prefix=C:\Users\msperka\AppData\Local\Temp\pip-install-0v2mk5c2\jq_4a9e3edbb5d04d8faa98d65c0fd5f0ea\_deps\build\onig-install-6.9.8
      error: [WinError 2] The system cannot find the file specified
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects`

**Comment by mwilliamson** [comment] 2023-12-26 10:50
I'm afraid Windows isn't supported. Closing as a duplicate of #20.

**Closed by mwilliamson** 2023-12-26 10:50 UTC
